# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c71652b83f928a7d4cc457c36bcb722bb87dc75ea4e01c05c54759d2da7e8024104fe613a87d8b389e4c4bdcbd5f4b73f9a268f58d7bce93e6eb009c5d9260f

test:
  secret_key_base: a253aa75a73e8f6dca821ba8f90b4b1ea52c2499a9323df9c1b0a5917ab0424e0b9a16cad82629e69c07800425c8d46e10a824bd69653a105463c8b4aed7eb1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
